#!/usr/bin/env bash

set -e

BASE_DIR=$(pwd -P)
CURRENT_SHA=$(git rev-parse --short HEAD)
CONFIG=config.toml

if [ ! -z ${PA11Y+x} ]; then
  CONFIG+=,hugo-pa11y.toml
fi

rm -rf $BASE_DIR/public
hugo --config $CONFIG
