#!/usr/bin/env bash

set -e

BASE_DIR=$(pwd -P)
CURRENT_SHA=$(git rev-parse --short HEAD)

# Generate CSS
rm -rf $BASE_DIR/static/css/gen
sass static/scss/index.scss:static/css/gen/index.css --style compressed

rm -rf $BASE_DIR/public
hugo
